### ISSUE TITLE
geetest not working

### ISSUE THREAD

**Issue by daUnknownCoder** [seriaati/hoyo-buddy#210]
hi, im loving hoyo-buddy, but when i did `/characters` for my genshin account, it said some `geetest` is required, so i clicked the button and nothing happens...

![image](https://github.com/user-attachments/assets/9f65b1d0-05ed-4687-b6af-314ac3c92a71) -> geetest ask
![image](https://github.com/user-attachments/assets/a1398aa6-9445-443d-81c8-520cde98b11f) -> nothing happening

discord: `daunknownguy`

generated link: https://geetest-server-test.seria.moe/captcha?user_id=_ig_this_is_private&message_id=this_might_be_private_too&channel_id=this_shouldnt_be_private_but_still&gt_version=3&api_server=api.geetest.com&gt_type=Real-time%20notes&account_id=4289&locale=en-US

**Comment by seriaati** [comment]
Thanks for writing this bug report, this issue is being investigated.

**Comment by seriaati** [comment]
Forgot to mention: You can workaround this bug by going to the official HoYoLAB website, login with the account that requires geetest, and go to "battle chronicle". A verification might pop up, it's fine if it doesn't, wait until the page is fully loaded, then go back to Hoyo Buddy and try the command again.
@daUnknownCoder

**Comment by daUnknownCoder** [comment]
"battle chronicle" im already logged into battle chronicle

wait what, i just went and did `/characters` today and it worked without `geetest`
sorry to waste your time, looks like a me problem, ill be closing this, and keep up the good work

a suggestion you may want to overlook, but can you make some image of build like battle chronicle or paimon.moe or enka.network does?

**Comment by daUnknownCoder** [comment]
this happened again, and the geetest didnt do anything, i went to battle schronicle page and there was a verification stuff, i did that hoyo verification and it started working again but yeah the geetest website is still not doing anything

**Comment by seriaati** [comment]
This is fixed in the next release, thanks for reporting this issue!

**Comment by daUnknownCoder** [comment]
heyoo, i didnt think i should be creating a new issue for this, so just adding a follow-up here:
im not able to use the `third party template`

![image](https://github.com/user-attachments/assets/e3e81a16-65a9-4d84-998b-8b12fca59fbf)

![image](https://github.com/user-attachments/assets/af583761-b071-4aed-975b-34a92c15630f)

so only the `ENCard Template 1` doesnt work

and yeah wha is the `Select Build` button? coz its unclickable
![image](https://github.com/user-attachments/assets/7919b2bc-9978-4ad9-8b8e-4517a5452102)

**Comment by seriaati** [comment]
You should open a new issue for this, it's entirely unrelated to this issue.

**Comment by daUnknownCoder** [comment]
> You should open a new issue for this, it's entirely unrelated to this issue.

yah i thought so, but also felt this is a me problem so probably thought to ask if this is an issue or just some problem on my end, thanks for the heads up, ill open a new issue
