### ISSUE TITLE
unable to use Third Party Template Card: `ENCard Template 1`

### ISSUE THREAD

**Issue by daUnknownCoder** [seriaati/hoyo-buddy#216]
yoo @seriaati, im not able to use the `third party template`

![image](https://github.com/user-attachments/assets/4ddbe04f-15ea-4ac4-a671-b773d32461f2)

![image](https://github.com/user-attachments/assets/97f0178b-2a1f-47f2-bc07-9834856033b4)

so only the `ENCard Template 1` doesnt work

**Comment by seriaati** [comment]
Hi, thanks for reporting this issue. I've been taking a break on HB development to work on school-related stuff. This will be fixed in the next release.

**Comment by seriaati** [comment]
Fixed.

**Comment by daUnknownCoder** [comment]
cool bro, all the best for your studies
